name: Mondoo Action
description: Mondoo Actions to scan IaC configs, containers, servers, clouds, and Kubernetes
branding:
  icon: "shield"
  color: "purple"
inputs:
  args:
    description: >-
      Additional arguments to pass to cnspec client.
    required: false
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec"
  args:
    - ${{ inputs.args }}
    - --output
    - ${{ inputs.output }}
    - --log-level
    - ${{ inputs.log-level }}
