name: Mondoo Action
description: Mondoo Actions to scan IaC configs, containers, servers, clouds, and Kubernetes
branding:
  icon: "shield"
  color: "purple"
inputs:
  args:
    description: >-
      Additional arguments to pass to cnspec client.
    required: false
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
runs:
  using: "composite"
  steps:
    - uses: "docker://mondoo/cnspec:7"
      with:
        args: ${{ inputs.args }} --log-level "${{ inputs.log-level }}"
