name: Mondoo Scan
author: Mondoo
description: Use Mondoo Client to scan repository contents
inputs:
  service_account_credentials:
    description: The Mondoo service account credentials. These should be stored in a GitHub secret and not set in the workflow configuration file directly.
    required: true
  docker_image_name:
    description: The Docker image to scan with Mondoo Client. This can be an image in DockerHub or a SHA from an earlier GitHub Action build step.
    required: false
  path:
    description: The file to scan with Mondoo Client
    required: false
  scan_type:
    description: The scan type to perform (docker_image, docker_image_from_dockerfile, k8s, or terraform)
    required: true
  score_threshold:
    required: false
    description: The score threshold for scans. If any score falls below the threshold, exit 1 (default 0).
    default: '0'
  output_format:
    description: Set the output format (compact|full|csv|json|junit|yaml). Default compact
    required: false
    default: 'compact'
  extra_args:
    description: Specify extra Mondoo Client scan arguments
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.scan_type }}" ]; then
          echo "The 'scan_type' input must be set for the Mondoo GitHub Action to run." >&2
          exit 1
        fi
        if [[ ! "${{ inputs.scan_type }}" =~ ^docker_image$|^docker_image_from_dockerfile$|^k8s$|^terraform$ ]]; then
          echo "Valid 'scan_type' input values are 'docker_image', 'docker_image_from_dockerfile', 'k8s', or 'terraform'. Cannot continue."
          exit 1
        fi
        if [[ "${{ inputs.scan_type }}" == "docker_image" ]] && [[ -z "${{ inputs.docker_image_name }}" ]]; then
          echo "When setting the 'scan_type' to 'docker_image' you must also specify the 'docker_image_name' input value. Cannot continue."
          exit 1
        fi
        if [[ "${{ inputs.scan_type }}" == "docker_image_from_dockerfile" ]] && [[ -z "${{ inputs.path }}" ]]; then
          echo "When setting the 'scan_type' to 'docker_image_from_dockerfile' you must also specify the 'path' input value. Cannot continue."
          exit 1
        fi
        if [[ "${{ inputs.scan_type }}" == "terraform" ]] && [[ -z "${{ inputs.path }}" ]]; then
          echo "When setting the 'scan_type' to 'terraform' you must also specify the 'path' input value. Cannot continue."
          exit 1
        fi
        if [[ ! "${{ inputs.output_format }}" =~ ^compact$|^full$|^csv$|^json$|^junit$|^yaml$ ]]; then
          echo "Valid 'output_format' input values are 'compact', 'full', 'csv', 'json', 'junit', or 'yaml'. Cannot continue."
          exit 1
        fi
        if [[ ! "${{ inputs.score_threshold }}" =~ ^([0-9]{,2}|100)$ ]]; then
          echo "Valid 'score_threshold' input values '0-100'. Cannot continue."
          exit 1
        fi
    - name: Install Mondoo Client
      shell: bash
      run: |
          echo Installing Mondoo Client...
          echo ${{ inputs.service_account_credentials }} | base64 -d > mondoo.json
          curl -sSL https://mondoo.com/install.sh | bash
    - name: Build the Docker Container
      shell: bash
      run: |
        echo Building mondoo-test-image from Dockerfile...
        docker build . --file ${{ inputs.path }} --tag mondoo-test-image
      if: inputs.scan_type == 'docker_image_from_dockerfile'
    
    # Only run for docker images or images from dockerfile
    - name: Scan docker container
      shell: bash
      run: |
        CONTAINER_IMAGE="${{ inputs.docker_image_name }}"
        if [ -z "$CONTAINER_IMAGE" ]; then
          CONTAINER_IMAGE=mondoo-test-image
        fi

        echo Scanning Docker container ${CONTAINER_IMAGE} with Mondoo Client...
        mondoo scan --detect-cicd docker://${CONTAINER_IMAGE} --config mondoo.json --score-threshold ${{ inputs.score_threshold }} --output ${{ inputs.output_format }} ${{ inputs.extra_args }}
      if: inputs.scan_type == ^docker_image$|^docker_image_from_dockerfile$ && inputs.scan_type != ^k8s$|^terraform$
    # Only run on k8s manifests, where ```--path``` is required for manifests.
    - name: Scan k8s manifest
      shell: bash
      run: |
        echo Scanning ${{ inputs.path }} with Mondoo Client...
        mondoo scan --detect-cicd ${{ inputs.scan_type }} --path ${{ inputs.path }} --config mondoo.json --score-threshold ${{ inputs.score_threshold }} --output ${{ inputs.output_format }} ${{ inputs.extra_args }}
      if: inputs.scan_type == 'k8s' && inputs.scan_type != ^docker_image$|^docker_image_from_dockerfile$|^terraform$
    # Only run on Terraform manifests, where a path is required and ```--path``` isn't supported.
    - name: Scan Terraform configuration files
      shell: bash
      run: |
        echo Scanning ${{ inputs.path }} with Mondoo Client...
        mondoo scan --detect-cicd ${{ inputs.scan_type }} ${{ inputs.path }} --config mondoo.json --score-threshold ${{ inputs.score_threshold }} --output ${{ inputs.output_format }} ${{ inputs.extra_args }}
      if: inputs.scan_type == 'terraform' && inputs.scan_type != ^docker_image$|^docker_image_from_dockerfile$|^k8s$

branding:
  icon: 'shield'
  color: 'purple'
