name: Mondoo Scan
author: Mondoo
description: Use Mondoo Client to scan repository contents
inputs:
  service_account_credentials:
    description: The Mondoo service account credentials. These should be stored in a GitHub secret and not set in the workflow configuration file directly.
    required: true
  path:
    description: The file to scan with Mondoo
    required: true
  scan_type:
    description: The scan type to perform (k8s or tf)
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Mondoo Client
      shell: bash
      run: |
          echo ${{ inputs.service_account_credentials }} | base64 -d > mondoo.json
          curl -sSL https://mondoo.com/install.sh | bash
    - name: Build the Docker Container
      shell: bash
      run: docker build . --file ${{ inputs.path }} --tag mondoo-test-image
      if: ${{ inputs.scan_type == 'docker' }}
    - name: Install container inspection tooling
      shell: bash
      run: sudo apt-get install rpm -y
      if: ${{ inputs.scan_type == 'docker' }}
    - name: Scan docker container
      shell: bash
      run: mondoo scan -t docker://mondoo-test-image --config mondoo.json
      if: ${{ inputs.scan_type == 'docker' }}
    - name: Scan configs
      shell: bash
      run: mondoo scan -t ${{ inputs.scan_type }}} --path ${{ inputs.path }} --config mondoo.json
      if: ${{ inputs.scan_type != 'docker' }}
          
branding:
  icon: 'shield'
  color: 'purple'
