name: "Mondoo Policy Action"
description: "A GitHub Action to add Mondoo policies on Mondoo Platform."
branding:
  icon: "shield"
  color: "purple"
inputs:
  action:
    description: >-
      Sets the action for cnspec bundle command: publish, validate (default "validate")
    default: validate
    required: false
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  path:
    description: Path to policy bundle
    required: true
  service-account-credentials:
    description: "Base64 encoded service account credentials used to authenticate with Mondoo Platform"
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec:7"
  args:
    - bundle
    - ${{ inputs.action }}
    - ${{ inputs.path }}
    - --log-level
    - ${{ inputs.log-level }}
  env:
    MONDOO_CONFIG_BASE64: ${{ inputs.service-account-credentials }}
