name: "Mondoo Policy Action"
description: "A GitHub Action to add Mondoo policies on Mondoo Platform."
branding:
  icon: "shield"
  color: "purple"
inputs:
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  path:
    description: Path to the policy file.
    required: true
runs:
  using: "docker"
  image: "docker://mondoo/cnspec:7"
  args:
    - bundle
    - upload
    - ${{ inputs.path }}
    - --log-level
    - ${{ inputs.log-level }}
