name: "Mondoo Policy Action"
description: "A GitHub Action to add Mondoo policies on Mondoo Platform."
branding:
  icon: "shield"
  color: "purple"
inputs:
  args:
    description: >-
      Additional arguments to pass to Mondoo Client.
    required: false
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  path:
    description: Path to the policy file.
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/mondoohq/actions:v0"
  args:
    - policy
    - add
    - ${{ inputs.path }}
    - --output
    - ${{ inputs.output }}
    - --score-threshold
    - ${{ inputs.score-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
    - ${{ inputs.args }}
