name: "Mondoo Terraform Plan GitHub Action"
description: "Scan HashiCorp Terraform Plan (JSON) for misconfigurations with Mondoo"
branding:
  icon: "shield"
  color: "purple"
inputs:
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  path:
    description: Path to the directory containing the plan file.
    default: terraform
    required: false
  plan-file:
    description: JSON plan file to scan.
    default: plan.json
    required: false
  score-threshold:
    description: >-
      Deprecated: Use `risk-threshold` instead.
    default: "0"
    required: false
  risk-threshold:
    description: >-
      Sets the score threshold for scans. Scores that fall below the threshold will exit 1. (default "0" - job continues regardless of the score returned by a scan).
    default: "0"
    required: false
  service-account-credentials:
    description: "Base64 encoded service account credentials used to authenticate with Mondoo Platform"
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec:12"
  args:
    - scan
    - terraform
    - plan
    - ${{ inputs.path }}/${{ inputs.plan-file }}
    - --output
    - ${{ inputs.output }}
    - --risk-threshold
    - ${{ inputs.risk-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
  env:
    MONDOO_CONFIG_BASE64: ${{ inputs.service-account-credentials }}
