name: "Mondoo Terraform State GitHub Action"
description: "Scan HashiCorp Terraform State for misconfigurations with Mondoo"
branding:
  icon: "shield"
  color: "purple"
inputs:
  args:
    description: >-
      Additional arguments to pass to Mondoo Client.
    required: false
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  path:
    description: Path to the Terraform working directory.
    required: true
  score-threshold:
    description: >-
      Sets the score threshold for scans. Scores that fall below the threshold will exit 1. (default "0" - job continues regardless of the score returned by a scan).
    default: "0"
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/mondoohq/actions:v0"
  args:
    - scan
    - terraform
    - state
    - ${{ inputs.path }}
    - --output
    - ${{ inputs.output }}
    - --score-threshold
    - ${{ inputs.score-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
    - ${{ inputs.args }}
