name: "Mondoo Github Organization Action"
description: "Scan Github organizations for misconfigurations with Mondoo"
branding:
  icon: "shield"
  color: "purple"
inputs:
  args:
    description: >-
      Additional arguments to pass to Mondoo Client.
    required: false
  organization:
    description: GitHub Organization
    required: true
  token:
    description: GitHub Authentication Token
    required: true
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  score-threshold:
    description: >-
      Sets the score threshold for scans. Scores that fall below the threshold will exit 1. (default "0" - job continues regardless of the score returned by a scan).
    default: "0"
    required: false
  is-cicd:
    description: "Automatically detects the GitHub Action Runs and report results into the CI/CD view"
    default: true
runs:
  using: "docker"
  image: "docker://mondoo/cnspec"
  args:
    - scan
    - github
    - org
    - ${{ inputs.organization }}
    - --discover
    - repository
    - --token
    - "${{ inputs.token }}"
    - --output
    - ${{ inputs.output }}
    - --score-threshold
    - ${{ inputs.score-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
    - --detect-cicd
    - ${{ inputs.is-cicd }}
    - ${{ inputs.args }}
