name: "Mondoo GitHub Organization Action"
description: "Scan GitHub organizations for misconfigurations with Mondoo"
branding:
  icon: "shield"
  color: "purple"
inputs:
  organization:
    description: GitHub Organization
    required: true
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format for scan results: compact, yaml, json, junit, csv, summary, full, report (default "compact")
    default: compact
    required: false
  score-threshold:
    description: >-
      Sets the score threshold for scans. Scores that fall below the threshold will exit 1. (default "0" - job continues regardless of the score returned by a scan).
    default: "0"
    required: false
  is-cicd:
    description: "Automatically detects the GitHub Action Runs and report results into the CI/CD view"
    default: true
  service-account-credentials:
    description: "Base64 encoded service account credentials used to authenticate with Mondoo Platform"
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec:11"
  args:
    - scan
    - github
    - org
    - ${{ inputs.organization }}
    - --discover
    - repository
    - --output
    - ${{ inputs.output }}
    - --score-threshold
    - ${{ inputs.score-threshold }}
    - --log-level
    - ${{ inputs.log-level }}
    - --detect-cicd=${{ inputs.is-cicd }}
  env:
    MONDOO_CONFIG_BASE64: ${{ inputs.service-account-credentials }}
