name: Setup Mondoo Action
description: Installs Mondoo Client into a workflow
inputs:
  log-level:
    description: >-
      Sets the log level: error, warn, info, debug, trace (default "info")
    default: info
    required: false
  output:
    description: >-
      Set the output format: yaml, json (default "json")
    default: json
    required: false
runs:
  using: "docker"
  image: "docker://mondoo/cnspec"
  args:
    - status
    - --output
    - ${{ inputs.output }}
    - --log-level
    - ${{ inputs.log-level }}
