name: Test cnspec policy linting

on:
  pull_request:
    paths:
      - "cnspec-lint/**"
      - ".github/test_files/**"
      - ".github/workflows/cnspec-lint.yaml"
  push:
    paths:
      - "cnspec-lint/**"
      - ".github/test_files/**"
      - ".github/workflows/cnspec-lint.yaml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Lint Policies
        uses: ./cnspec-lint
        with:
          path: ./.github/test_files/cnspec-lint
          output-file: "custom-results.sarif"
      - name: Archive SARIF results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cnspec-lint-report
          path: custom-results.sarif
