name: General Mondoo action
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/test_files/**"
      - ".github/workflows/general-action.yaml"
  push:
    paths:
      - "action.yaml"
      - ".github/test_files/**"
      - ".github/workflows/general-action.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  general-action-test:
    runs-on: ubuntu-latest
    name: Test general Mondoo action
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Show status
        uses: ./
        with:
          args: status
          service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
      - name: Show status
        uses: ./
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          args: status
      - name: Show version
        uses: ./
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          args: version
