name: General Mondoo action
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/general-action.yaml"
  push:
    paths:
      - "action.yaml"
      - ".github/workflows/general-action.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  general-action-test:
    runs-on: ubuntu-latest
    name: Test general Mondoo action
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Show status
        uses: ./
        with:
          args: status
          service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
      - name: Show status
        uses: ./
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          args: status
      - name: Show version
        uses: ./
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          args: version
