name: GitHub repo Scanning
on:
  pull_request:
    paths:
      - "github-repo/**"
      - ".github/workflows/github-repo.yaml"
  push:
    paths:
      - "github-repo/**"
      - ".github/workflows/github-repo.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  github-repo-tests:
    runs-on: ubuntu-latest
    name: Test GitHub repo scanning
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Scan GitHub repo
        uses: ./github-repo
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: mondoohq/actions
