name: K8s Manifest Scanning
on:
  pull_request:
    paths:
      - "k8s-manifest/**"
      - ".github/test_files/**"
      - ".github/workflows/k8s-manifest.yaml"
  push:
    paths:
      - "k8s-manifest/**"
      - ".github/test_files/**"
      - ".github/workflows/k8s-manifest.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  k8s-manifest-tests:
    runs-on: ubuntu-latest
    name: Test k8s manifest scanning
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan k8s manifest
        uses: ./k8s-manifest
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ./.github/test_files/k8s-manifest.yaml
      - name: Scan k8s directory
        uses: ./k8s-manifest
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ./.github/test_files/
