name: K8s Manifest Scanning
on:
  pull_request:
    paths:
      - "k8s-manifest/**"
      - ".github/test_files/**"
      - ".github/workflows/k8s-manifest.yaml"
  push:
    paths:
      - "k8s-manifest/**"
      - ".github/test_files/**"
      - ".github/workflows/k8s-manifest.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  k8s-manifest-tests:
    runs-on: ubuntu-latest
    name: Test k8s manifest scanning
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Scan k8s manifest
        uses: ./k8s-manifest
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ./.github/test_files/k8s-manifest.yaml
      - name: Scan k8s directory
        uses: ./k8s-manifest
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ./.github/test_files/
