name: Terraform Plan Scanning Tests
on:
  pull_request:
    paths:
      - "terraform-plan/**"
      - ".github/test_files/**"
      - ".github/workflows/terraform-plan.yaml"
  push:
    paths:
      - "terraform-plan/**"
      - ".github/test_files/**"
      - ".github/workflows/terraform-plan.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    name: Test Terraform scanning
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # run terraform plan checks
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          # super important setting, otherwise you cannot pipe terraform show -json
          # see https://stackoverflow.com/questions/66496105/how-can-i-remove-all-the-extraneous-output-from-redirected-output-in-github-acti
          terraform_wrapper: false
      - run: terraform init
        working-directory: ./.github/test_files/tfplan
      - name: Write terraform plan
        run: terraform plan -out plan
        working-directory: ./.github/test_files/tfplan
      - name: Export terraform plan to json
        shell: bash
        run: terraform show -json plan > plan.json
        working-directory: ./.github/test_files/tfplan
      - name: Upload terraform plan
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: terraform-plan.json
          path: .github/test_files/tfplan/plan.json
      - name: Scan Terraform Plan
        uses: ./terraform-plan
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ".github/test_files/tfplan/"
          plan-file: plan.json
      - name: Scan Terraform Plan (SARIF)
        uses: ./terraform-plan
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ".github/test_files/tfplan/"
          plan-file: plan.json
          output: sarif
          output-file: results.sarif
      - name: Archive SARIF results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: terraform-plan-report
          path: results.sarif
