name: Terraform HCL Scanning Tests
on:
  pull_request:
    paths:
      - "terraform-hcl/**"
      - ".github/test_files/**"
      - ".github/workflows/terraform-hcl.yaml"
  push:
    paths:
      - "terraform-hcl/**"
      - ".github/test_files/**"
      - ".github/workflows/terraform-hcl.yaml"
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    name: Test Terraform scanning
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan Terraform HCL
        uses: ./terraform-hcl
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        with:
          path: ./.github/test_files/tf
