name: Test xgrep scanning

on:
  pull_request:
    paths:
      - "xgrep/**"
      - ".github/test_files/xgrep/**"
      - ".github/workflows/xgrep.yaml"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Run xgrep
        uses: ./xgrep
        with:
          path: ./.github/test_files/xgrep
          output-file: "custom-results.sarif"
      - name: Archive SARIF results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: xgrep-report
          path: custom-results.sarif
